name: docs

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install markdownlint-cli2
        run: npm ci || npm i -D markdownlint-cli2
      - name: Run markdownlint
        run: npx markdownlint-cli2 "**/*.md" "!site/**"

      - name: Vale Lint
        uses: errata-ai/vale-action@v2
        with:
          files: "docs/**/*.md"
          config: .vale.ini

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mkdocs-material
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      - name: Build (strict)
        run: mkdocs build --strict

  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: [lint, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mkdocs-material
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      - name: Build
        run: mkdocs build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
